"""add_calibration_expiry

Revision ID: 2e1830eff43c
Revises: d23304250222
Create Date: 2026-02-13 08:53:53.502032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1830eff43c'
down_revision: Union[str, None] = 'd23304250222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_calibration', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('backtest_calibration', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('tournament_calibration', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournament_calibration', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_calibration', 'is_active')
    op.drop_column('tournament_calibration', 'expires_at')
    op.drop_column('backtest_calibration', 'is_active')
    op.drop_column('backtest_calibration', 'expires_at')
    # ### end Alembic commands ###
