"""add_cbb_player_game_log_table

Revision ID: 62db67f9d49a
Revises: 8142d7eaf8e5
Create Date: 2026-03-17 11:34:02.451815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62db67f9d49a'
down_revision: Union[str, None] = '8142d7eaf8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
