"""Add sport column to player_minutes_history

Revision ID: 8142d7eaf8e5
Revises: f82a3b19c7d0
Create Date: 2026-03-16 22:26:07.737907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8142d7eaf8e5'
down_revision: Union[str, None] = 'f82a3b19c7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expert_signal_log', 'mentioned_team',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.add_column('nba_injuries', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('nba_injuries', sa.Column('official_status', sa.String(length=32), nullable=True))
    op.add_column('nba_injuries', sa.Column('effective_factor', sa.Float(), nullable=True))
    op.add_column('nba_injuries', sa.Column('consecutive_dnp_count', sa.Integer(), nullable=True))
    op.create_index('ix_nba_inj_factor', 'nba_injuries', ['effective_factor'], unique=False)
    op.create_index('ix_nba_inj_team_id', 'nba_injuries', ['team_id'], unique=False)
    op.create_index(op.f('ix_nba_injuries_team_id'), 'nba_injuries', ['team_id'], unique=False)
    op.add_column('player_minutes_history', sa.Column('sport', sa.String(length=3), nullable=False, server_default='nba'))
    op.add_column('player_minutes_history', sa.Column('actual_fg3a_rate', sa.Float(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('actual_fga_rate', sa.Float(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('actual_fta_rate', sa.Float(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('actual_fg3_pct', sa.Float(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('actual_fg2_pct', sa.Float(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('actual_ft_pct', sa.Float(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('opponent_team_id', sa.Integer(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('projected_fg3a_rate', sa.Float(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('projected_fga_rate', sa.Float(), nullable=True))
    op.add_column('player_minutes_history', sa.Column('projected_fta_rate', sa.Float(), nullable=True))
    op.create_index(op.f('ix_player_minutes_history_opponent_team_id'), 'player_minutes_history', ['opponent_team_id'], unique=False)
    op.create_index(op.f('ix_player_minutes_history_sport'), 'player_minutes_history', ['sport'], unique=False)
    op.alter_column('player_prop_snapshot', 'team_abbreviation',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.add_column('projection_log', sa.Column('sport', sa.String(length=3), nullable=False, server_default='nba'))
    op.create_index(op.f('ix_projection_log_sport'), 'projection_log', ['sport'], unique=False)
    op.add_column('teams', sa.Column('sport', sa.String(length=3), nullable=False, server_default='nba'))
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_constraint(op.f('teams_abbreviation_key'), 'teams', type_='unique')
    op.create_index(op.f('ix_teams_sport'), 'teams', ['sport'], unique=False)
    op.create_unique_constraint('uq_teams_abbr_sport', 'teams', ['abbreviation', 'sport'])
    op.add_column('tournament_contest', sa.Column('sport', sa.String(length=3), nullable=False, server_default='nba'))
    op.create_index(op.f('ix_tournament_contest_sport'), 'tournament_contest', ['sport'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_contest_sport'), table_name='tournament_contest')
    op.drop_column('tournament_contest', 'sport')
    op.drop_constraint('uq_teams_abbr_sport', 'teams', type_='unique')
    op.drop_index(op.f('ix_teams_sport'), table_name='teams')
    op.create_unique_constraint(op.f('teams_abbreviation_key'), 'teams', ['abbreviation'], postgresql_nulls_not_distinct=False)
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.drop_column('teams', 'sport')
    op.drop_index(op.f('ix_projection_log_sport'), table_name='projection_log')
    op.drop_column('projection_log', 'sport')
    op.alter_column('player_prop_snapshot', 'team_abbreviation',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.drop_index(op.f('ix_player_minutes_history_sport'), table_name='player_minutes_history')
    op.drop_index(op.f('ix_player_minutes_history_opponent_team_id'), table_name='player_minutes_history')
    op.drop_column('player_minutes_history', 'projected_fta_rate')
    op.drop_column('player_minutes_history', 'projected_fga_rate')
    op.drop_column('player_minutes_history', 'projected_fg3a_rate')
    op.drop_column('player_minutes_history', 'opponent_team_id')
    op.drop_column('player_minutes_history', 'actual_ft_pct')
    op.drop_column('player_minutes_history', 'actual_fg2_pct')
    op.drop_column('player_minutes_history', 'actual_fg3_pct')
    op.drop_column('player_minutes_history', 'actual_fta_rate')
    op.drop_column('player_minutes_history', 'actual_fga_rate')
    op.drop_column('player_minutes_history', 'actual_fg3a_rate')
    op.drop_column('player_minutes_history', 'sport')
    op.drop_index(op.f('ix_nba_injuries_team_id'), table_name='nba_injuries')
    op.drop_index('ix_nba_inj_team_id', table_name='nba_injuries')
    op.drop_index('ix_nba_inj_factor', table_name='nba_injuries')
    op.drop_column('nba_injuries', 'consecutive_dnp_count')
    op.drop_column('nba_injuries', 'effective_factor')
    op.drop_column('nba_injuries', 'official_status')
    op.drop_column('nba_injuries', 'team_id')
    op.alter_column('expert_signal_log', 'mentioned_team',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
    # ### end Alembic commands ###
