"""add_indexes_and_constraints

Revision ID: d61e2f22188e
Revises: 4fa870d2d1b9
Create Date: 2026-02-13 10:00:49.428078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61e2f22188e'
down_revision: Union[str, None] = '4fa870d2d1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ai_usage_agent_created', 'ai_usage_log', ['agent_name', 'created_at'], unique=False)
    op.create_index('ix_bc_active_expiry', 'backtest_calibration', ['is_active', 'expires_at'], unique=False)
    op.create_index(op.f('ix_player_minutes_history_position'), 'player_minutes_history', ['position'], unique=False)
    op.create_unique_constraint('uq_pmh_player_game_date', 'player_minutes_history', ['player_id', 'game_date'])
    op.create_index('ix_tcal_active_expiry', 'tournament_calibration', ['is_active', 'expires_at'], unique=False)
    op.create_index('ix_te_contest_winner', 'tournament_entry', ['contest_id_fk', 'is_winner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_te_contest_winner', table_name='tournament_entry')
    op.drop_index('ix_tcal_active_expiry', table_name='tournament_calibration')
    op.drop_constraint('uq_pmh_player_game_date', 'player_minutes_history', type_='unique')
    op.drop_index(op.f('ix_player_minutes_history_position'), table_name='player_minutes_history')
    op.drop_index('ix_bc_active_expiry', table_name='backtest_calibration')
    op.drop_index('ix_ai_usage_agent_created', table_name='ai_usage_log')
    # ### end Alembic commands ###
